import ThemeProvider from "@/components/theme-provider";
import SessionProvider from "@/components/session-provider";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider> {children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
